name: manylinux_wheel

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://konstin2/maturin:master
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: maturin build --release
    - name: Upload wheel to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        python upload_artifact.py -d target/wheels
